app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
 */

Route::group(array('before' => 'auth'), function () {

	Route::group(array('prefix' => 'users'), function(){

		Route::get('/search', 'UserController@search');
		Route::get('/{users}/edit/schedules', 'UserController@editSchedules');
		Route::post('/{users}/edit/schedules', 'UserController@createSchedules');
		Route::post('/{users}/edit/schedules/{sid}', 'UserController@updateSchedules');
		Route::delete('/{users}/edit/schedules/{sid}/destroy', 'UserController@destroySchedules');

		Route::get('/{users}/edit/appointments/{sid?}', 'UserController@editAppointments');
		Route::delete('/{users}/edit/appointments/{sid?}/destroy', 'UserController@destroyAppointments');
		Route::get('/{users}/show/appointments/{sid?}', 'UserController@showAppointments');
		
		Route::get('/{users}/show/assessments/{sid?}', 'UserController@showAssessments');

	});

	Route::resource('users', 'UserController');

	Route::get('attachments/{id}/destroy', 'AttachmentController@destroy');
	Route::get('attachments/{id}/destroyUrl', 'AttachmentController@destroyUrl');
	Route::resource('attachments', 'AttachmentController', array('only' => array('show')));

	Route::post('courses/{id}/edit/lessons/reorder', 'SyllabusController@reorder');
	Route::resource('courses/{id}/edit/lessons', 'SyllabusController', array('except' => array('show', 'create', 'edit')));
	Route::get('courses/{id}/edit/exam', 'SyllabusController@exam');
	Route::get('courses/{id}/lessons', array(
		'as' => 'courses.show.lessons', 
		'uses' => 'CourseController@show'
	));
	Route::get('courses/{id}/exams', array(
		'as' => 'courses.show.exam', 
		'uses' => 'CourseController@exam'
	));
	Route::resource('courses', 'CourseController');

	Route::get('schedules/{id}/edit/students', 'ScheduleController@editStudents');
	Route::resource('schedules', 'ScheduleController', array('except' => array('show')));

	Route::get('appointment/list/{year?}/{month?}/{day?}', 'AppointmentController@listIndex');
	Route::get('appointment/exam/{year?}/{month?}', 'AppointmentController@listExam');
	Route::get('appointment/events/{sid?}', 'AppointmentController@getEvents');
	Route::post('appointment/events/add', 'AppointmentController@addEventStudent');
	Route::post('appointment/events/delete', 'AppointmentController@deleteEventStudent');

	Route::get('appointment/{id}/students', 'AppointmentController@getStudents');
	Route::post('appointment/{id}/students', 'AppointmentController@addStudent');
	Route::post('appointment/{id}/students/delete', 'AppointmentController@deleteStudent');

	Route::get('appointment/{id}/lessons', 'AppointmentController@getLesson');
	Route::post('appointment/{id}/lessons', array(
		'as' => 'appointment.lesson.add', 
		'uses' => 'AppointmentController@addLesson'
	));
	Route::post('appointment/{id}/lessons/delete', array(
		'as' => 'appointment.lesson.delete', 
		'uses' => 'AppointmentController@deleteLesson'
	));
	Route::post('appointment/{id}/lessons/auto', array(
		'as' => 'appointment.lesson.choose', 
		'uses' => 'AppointmentController@chooseAuto'
	));
	/*Route::post('appointment/{id}/lessons/auto', array(
		'as' => 'appointment.lesson.auto', 
		'uses' => 'AppointmentController@toggleAuto'
	));*/

	Route::get('appointment/{id}/attendance', 'AppointmentController@getAttend');
	Route::post('appointment/{id}/attendance/update', array(
		'as' => 'appointment.attend.update', 
		'uses' => 'AppointmentController@updateAttend')
	);

	Route::get('appointment/{id}/remarks', 'AppointmentController@getRemarks');
	Route::post('appointment/{id}/remarks/update', array(
		'as' => 'appointment.remarks.update', 
		'uses' => 'AppointmentController@updateRemarks')
	);
	Route::resource('appointment', 'AppointmentController');

	Route::get('reports/{uid}/{sid}', 'ReportController@getReport');

	Route::resource('setting/notification', 'Setting\\NotificationController', array('except' => array('show')));
	Route::controller('setting', 'SettingController');

	Route::controller('dashboard', 'HomeController');

	Route::controller('mbti', 'PsychologyTestController');

	Route::get('/', 'HomeController@getIndex');

});

/*
Route::group(array('prefix' => 'demo'), function(){

	Route::get('/assessment', function(){
		$data['questions'] = Config::get('question.ver2');
		$data['assets_version'] = 2;

		return View::make('demo.assessment', $data);
	});

	Route::get('/history', function(){
		$data['questions'] = Config::get('question.ver2');
		$data['assets_version'] = 2;

		return View::make('demo.history', $data);
	});

});*/

/*Route::get('update', function(){
	Artisan::call('migrate', array('--force' => true));
});*/

//Route::controller('/utility', 'DevController');

Route::controller('/', 'AuthController');

app/models/User.php
<?php

use Illuminate\Auth\Reminders\RemindableInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\UserTrait;

class User extends Eloquent implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait, SoftDeletingTrait;

	protected $table = 'users';

	protected $fillable = array('email', 'address', 'age', 'phone', 'remarks', 'avatar', 'start_date', 'remember_token', 'is_inactive');

	protected $guarded = array('id', 'ref_id', 'ic', 'name', 'role', 'password');

	protected $dates = array('deleted_at');

	protected $appends = array('role_name', 'sd_day', 'sd_month', 'sd_year');

	public function getAgeAttribute($value) {
		return (($value == null) or ($value == '') or ($value == 0)) ? '' : $value;
	}

	public function getRefIdAttribute($value) {
		return (($value == null) or ($value == '')) ? '' : $value;
	}

	public function getRoleNameAttribute($value) {
		$role = $this->attributes['role'];
		if ($role == 1) {
			$name = 'Admin';
		} elseif ($role == 2) {
			$name = 'Teacher';
		} else {
			$name = 'Student';
		}
		return $name;
	}

	public function getSdDayAttribute() {
		return date_parse_from_format('Y-m-d', $this->attributes['start_date'])['day'];
	}

	public function getSdMonthAttribute() {
		return date_parse_from_format('Y-m-d', $this->attributes['start_date'])['month'];
	}

	public function getSdYearAttribute() {
		return date_parse_from_format('Y-m-d', $this->attributes['start_date'])['year'];
	}

	public function setPasswordAttribute($value) {
		$this->attributes['password'] = Hash::make($value);
	}

	public function setNameAttribute($value) {
		$this->attributes['name'] = ucwords(strtolower($value));
	}

	public function acl() {
		return $this->hasMany('Acl', 'role_id', 'role');
	}

	public function schedules() {
		if(!isset($this->attributes['role']))
			return null;

		if ($this->attributes['role'] == 3) {
			return $this->belongsToMany('Schedule', 'schedules_students', 'user_id', 'schedule_id')->withPivot('start_date', 'expiry_date', 'total_session', 'used_session', 'exam', 'used_exam', 'miss_count', 'deleted_at', 'id')->withTimestamps();
		} else {
			return $this->belongsToMany('Schedule', 'schedules_tutors', 'user_id', 'schedule_id');
		}
	}

	public function notifications()
	{
		return $this->hasMany('Notification', 'user_id');
	}

	public function appointments() {
		return $this->belongsToMany('Appointment', 'appointments_users', 'user_id', 'appointment_id')->withTimestamps()->withPivot('syllabus_id', 'is_exam', 'is_missed');
	}

	public function remarks(){
		return $this->hasMany('Remarks', 'student_id', 'id');
	}

}

app/controllers/UserController.php
<?php

class UserController extends \BaseController {

	protected $layout = "layout";

	protected $active = "user";

	public function __construct(Processes\User $user) {
		parent::__construct();

		$this->user = $user;

		$this->beforeFilter('@onlyAdmin', array('except' => array('show', 'showAppointments', 'showAssessments')));
		$this->beforeFilter('@onlyCu', array('only' => array('show', 'showAssessments', 'showAppointments')));
	}

	public function onlyAdmin($route, $request){

		$role = $this->data['cu']->role;
		$uid = $this->data['cu']->id;

		if($role > 1) return Redirect::action('UserController@show', array($uid));

	}

	public function onlyCu($route, $request){

		$role = $this->data['cu']->role;
		$uid = $this->data['cu']->id;

		if(($role == 3) && ($route->parameter('users') != $uid)) return Redirect::action('UserController@show', array($uid));		

	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index() {
		$this->data['role'] = $this->user->role_filter(Input::get('role', '3'));
		$this->data['inactive'] = Input::get('inactive', false);
		$this->data['users'] = $this->user->get($this->data['role'], 50, $this->data['inactive']);
		$this->data['paginator'] = $this->data['users']->appends(array('role' => $this->data['role'], 'inactive' => $this->data['inactive']))->links();
		$this->data['user_count'] = array(
			'student' 	=> $this->user->count(3),
			'inactive'	=> $this->user->count(3,1),
			'teacher'	=> $this->user->count(2),
			'admin'		=> $this->user->count(1)
		);

		$this->layout->with($this->data);
		$this->layout->content = View::make('users.index', $this->data);
	}

	public function search() {
		$this->data['role'] = 'all';
		$this->data['users'] = $this->user->search(Input::get('q'), 50);
		$this->data['search'] = true;
		$this->data['user_count'] = array(
			'student' 	=> $this->user->count(3),
			'inactive'	=> $this->user->count(3,1),
			'teacher'	=> $this->user->count(2),
			'admin'		=> $this->user->count(1)
		);
		$this->data['paginator'] = $this->data['users']->appends(array('q' => Input::get('q')))->links();

		$this->layout->with($this->data);
		$this->layout->content = View::make('users.index', $this->data);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create() {
		$this->data['schedule'] = Schedule::all()->lists('name', 'id');
		$this->data['schedule'][-1] = 'None';
		ksort($this->data['schedule']);

		$this->layout->with($this->data);
		$this->layout->content = View::make('users.form', $this->data);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store() {
		return $this->user->save(Input::all(), Input::file('avatar'));
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id) {
		$this->data['id'] = $id;
		$this->data['user'] = User::findOrFail($id);
		$this->data['tabs'] = "schedules";
		$this->data['schedules'] = $this->data['user']->schedules;
		$this->data['appointments'] = $this->data['user']->appointments->groupBy('schedule_id');
		$this->data['exams'] = $this->data['user']->appointments->filter(function($a){
			return ($a->pivot->is_exam && !$a->pivot->is_missed);
		})->groupBy('schedule_id');
		$this->data['miss'] = $this->data['user']->appointments->filter(function($a) use ($id){
			return $a->attendance->filter(function($attend) use ($id){
				return (($attend->student_id == $id) && ($attend->attend == 0));
			})->count();
		})->groupBy('schedule_id');

		$this->data['is_current_user'] = ($id == $this->data['cu']->id);

		$this->layout->with($this->data);
		$this->layout->content = View::make('users.show', $this->data);
	}

	public function showAppointments($id, $sid = null){
		$this->data['id'] = $id;
		$this->data['sid'] = $sid;
		$this->data['tabs'] = "appointments";
		$this->data['user'] = User::findOrFail($id);

		if($this->data['user']->schedules->count() > 0){
			if(!isset($sid) || !$this->data['user']->schedules->contains($sid))
				$sid = $this->data['user']->schedules->first()->id;
			$this->data['schedule'] = $this->data['user']->schedules->lists('name', 'id');
			$this->data['appointments'] = $this->data['user']->appointments()->where('schedule_id', $sid)->orderBy('start_time')->get();
			$this->data['index'] = $this->data['user']->schedules->find($sid)->pivot->used_session;
			$this->data['max_miss'] = $this->data['user']->schedules->find($sid)->pivot->miss_count;
		}else{
			$this->data['schedule'] = array();
			$this->data['appointments'] = array();
		}

		$this->data['is_current_user'] = ($id == $this->data['cu']->id);

		$this->layout->with($this->data);
		$this->layout->content = View::make('users.show', $this->data);
	}

	public function showAssessments($id, $sid = null){
		$this->data['id'] = $id;
		$this->data['tabs'] = "assessments";
		$this->data['user'] = User::findOrFail($id);
		$this->data['ver'] = Input::get('ver');
		$this->data['qmeta'] = Config::get('question._meta.versions');
		if($this->data['user']->schedules->count() >= 1){
			//schedule list
			if(!isset($sid) || !$this->data['user']->schedules->contains($sid))
				$sid = $this->data['user']->schedules->first()->id;
			$this->data['schedule'] = $this->data['user']->schedules->lists('name', 'id');

			//get related assessment version
			$this->data['versions'] = $this->user->getRemarksVersion($id, $sid);
			if(!in_array($this->data['ver'], $this->data['versions']) && (count($this->data['versions']) > 0))
				$this->data['ver'] = $this->data['versions'][0];

			$after = null;
			$before = null;
			if(count($this->data['versions']) > 0){
				$index = array_search($this->data['ver'], $this->data['versions'])+1;
				if(isset($this->data['versions'][$index])){
					$after = $this->data['qmeta'][$this->data['versions'][$index]]." 23:59:59";
				}else{
					$after = null;
				}

				if($this->data['qmeta'][$this->data['ver']] == 'default'){
					$before = null;
				}else{
					$before = $this->data['qmeta'][$this->data['ver']].' 23:59:59';
				}
			}

			$this->data['remarks'] = $this->user->getRemarks($id, $sid, $after, $before);
		}else{
			$this->data['schedule'] = array();
		}

		$this->data['sid'] = $sid; 

		$this->data['questions'] =  Config::get('question.'.$this->data['ver']);

		$this->data['is_current_user'] = ($id == $this->data['cu']->id);

		$this->layout->with($this->data);
		$this->layout->content = View::make('users.show', $this->data);	
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id) {
		$this->data['id'] = $id;
		$this->data['user'] = User::findOrFail($id);

		$this->data['schedule'] = Schedule::all()->lists('name', 'id');
		$this->data['schedule'][-1] = 'None';
		ksort($this->data['schedule']);

		$this->layout->with($this->data);
		$this->layout->content = View::make('users.form', $this->data);
	}

	public function editSchedules($id){
		$this->data['id'] = $id;
		$this->data['schedules'] = User::findOrFail($id)->schedules;

		$this->data['schedule_list'] = Schedule::all()->lists('name', 'id');
		$this->data['schedule_list'][-1] = 'None';
		foreach($this->data['schedule_list'] as $key => $s){
			if($this->data['schedules']->contains($key))
				unset($this->data['schedule_list'][$key]);
		}
		ksort($this->data['schedule_list']);

		$this->layout->with($this->data);
		$this->layout->content = View::make('users.schedules', $this->data);
	}

	public function createSchedules($id){
		$input = Input::only('schedule_id', 'start_date', 'expiry_date', 'total_session', 'exam', 'used_exam', 'miss_count', 'used_session');

		$v = $this->user->validate_schedule($input, null, Redirect::action('UserController@editSchedules', array($id)));
		if(!($v === true))
			return $v;
		$this->user->save_schedule(User::findOrFail($id),$input);

		return Redirect::action('UserController@editSchedules', array($id))->with('msg_success', 'User added to new schedule.');
	}

	public function updateSchedules($id, $sid){
		$input = array(
			'schedule_id'	=> $sid,
			'start_date' 	=> Input::get('start_date.'.$sid),
			'expiry_date'	=> Input::get('expiry_date.'.$sid),
			'total_session'	=> Input::get('total_session.'.$sid),
			'exam'			=> Input::get('exam.'.$sid),
			'used_exam'		=> Input::get('used_exam.'.$sid),
			'miss_count'	=> Input::get('miss_count.'.$sid),
			'used_session'	=> Input::get('used_session.'.$sid)
		);
		$v = $this->user->validate_schedule($input, $sid, Redirect::action('UserController@editSchedules', array($id)));
		if(!($v === true))
			return $v;
		$this->user->save_schedule(User::findOrFail($id), $input);

		return Redirect::action('UserController@editSchedules', array($id))->with('msg_success', 'Schedule\'s settings updated.');
	}

	public function destroySchedules($id, $sid){
		$user = User::findOrFail($id);
		$user->schedules()->detach($sid);

		return Redirect::action('UserController@editSchedules', array($id))->with('msg_success', 'User\'s schedules deleted.');
	}

	public function editAppointments($id, $sid = null){
		$this->data['id'] = $id;
		$this->data['user'] = User::findOrFail($id);
		if($this->data['user']->schedules->count() > 0){
			if(!isset($sid) || !$this->data['user']->schedules->contains($sid))
				$sid = $this->data['user']->schedules->first()->id;
			$this->data['schedule'] = $this->data['user']->schedules->lists('name', 'id');
			$this->data['appointments'] = $this->data['user']->appointments()->where('schedule_id', $sid)->orderBy('start_time')->paginate(50);
			$this->data['index'] = $this->data['user']->schedules->find($sid)->pivot->used_session;
			$this->data['max_miss'] = $this->data['user']->schedules->find($sid)->pivot->miss_count;
		}else{
			$this->data['appointments'] = array();
			$this->data['schedule'] = array();
		}
		$this->data['sid'] = $sid;

		$this->layout->with($this->data);

app/views/users/appointments.blade.php
@extends('layout')

@section('breadcrumb')
	<li><a href="{{ action('UserController@index') }}">User Management</a></li>
	<li class="active">Edit User Schedules</li>
@stop

@section('page_title')
	<h1>Edit User</h1>
@stop

@section('page_action')
@if(isset($user))
<a href="{{ route('users.show', array($id)) }}" class="btn btn-primary">
	<i class="fa fa-eye"></i> View
</a>
{{ Form::open(array('action' => array('UserController@destroy', $user->id), 'method' => 'delete', 'class' => 'form-ib')) }}
	<button class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
{{ Form::close() }}
@endif
@stop

@section('header_css')
	<link rel="stylesheet" href="{{ asset('lib/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css') }}">
@stop

@section('footer_js')
<script src="{{ asset('lib/moment/moment.js') }}" type="text/javascript"></script>
<script type="text/javascript" src="{{ asset('lib/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/users.js') }}"></script>
@stop

@section('contents')
<div class="row">
	<div class="col-md-12">
		<ul class="nav nav-tabs">
		  	<li role="presentation"><a href="{{ route('users.edit', array($id)) }}">General Info</a></li>
		  	<li role="presentation"><a href="{{ action('UserController@editSchedules', array($id)) }}">Classes</a></li>
		  	<li role="presentation" class="active"><a href="{{ action('UserController@editAppointments', array($id)) }}">Appointments</a></li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div id="user-ap-helper">
			@if(isset($schedule) && (count($schedule) > 0))
			<form action="{{ action('UserController@editAppointments', array($id)) }}" class="form-inline">
				<div class="form-group">
					<label for="filter">Class Filter: </label>
					{{ Form::select('filter', $schedule, $sid, array('class' => 'form-control')) }}
					<button type="submit" class="btn btn-primary">Go</button>
				</div>
			</form>
			@else
				Student is not enrolled in any class.
			@endif
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="table-responsive">
			<table class="table table-striped table-bordered">
				<thead>
					<tr>
						<th>Id</th>
						<th>Date</th>
						<th>Time</th>
						<th>Lesson Plan</th>
						<th>Attendance</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php $missed = 0; ?>
					@forelse($appointments as $a)
					<?php 
						$attend = $a->attendance()->where('student_id', $id)->first(); 
						$is_missed = !(isset($attend->attend) && $attend->attend);
						if($is_missed) $missed++;
					?>
						<tr>
							<td>
								@if($attend == null)
									{{ ++$index }}
								@elseif($is_missed && ($missed <= $max_miss))
									-
								@else
									{{ ++$index }}
								@endif
							</td>
							<td>{{ date('Y-m-d', strtotime($a->start_time)) }}</td>
							<td>{{ date('H:i', strtotime($a->start_time)).' - '.date('H:i', strtotime($a->end_time)) }}</td>
							<td>
								@if(isset($a->pivot->syllabus_id))
									<?php $s = Syllabus::withTrashed()->find($a->pivot->syllabus_id) ?>
									{{ $s->name }} 
									{{ $s->is_exam ? '(Exam)' : '' }}
									{{ $s->deleted_at ? '(Deleted)' : '' }}
								@else
									-
								@endif
							</td>
							<td>
								@if($attend == null)
								-
								@else
								<i class="fa fa-{{ $is_missed ? 'close' : 'check' }}"></i>
								@endif
							</td>
							<td>
								<a href="{{ route('appointment.show', array($a->id)) }}" class="btn btn-primary"><i class="fa fa-eye"></i> View</a>
								<a href="{{ action('AppointmentController@edit', array($a->id)) }}" class="btn btn-warning"><i class="fa fa-pencil"></i> Edit</a>
								{{ Form::open(array('action' => array('UserController@destroyAppointments', $id, $a->id), 'method' => 'delete', 'class' => 'form-ib')) }}
								<button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Remove</button>
								{{ Form::close() }}
							</td>
						</tr>
					@empty
						<tr>
							<td colspan="6">No appointment in this class was found.</td>
						</tr>
					@endforelse
				</tbody>
				<tfoot>
					<tr>
						<td>Id</td>
						<td>Date</td>
						<td>Time</td>
						<td>Lesson Plan</td>
						<td>Attendance</td>
						<td>Action</td>
					</tr>
				</tfoot>
			</table>
			@if(count($appointments))
			{{ $appointments->links() }}
			@endif
		</div>
	</div>
</div>
@stop

app/views/users/new_index.blade.php
@extends('layout')

@section('breadcrumb')
	@if(isset($search) && $search == true)
	<li><a href="{{ action('UserController@index') }}">User Management</a></li>
	<li>Search</li>
	@else
	<li class="active"><a href="{{ action('UserController@index') }}">User Management</a></li>
	@endif
@stop

@section('page_title')
	<h1>User Management</h1>
	<h2>Browse and edit profiles of the users.</h2>
@stop

@section('page_action')
	<div class="row">
		<div class="col-sm-6 col-sm-offset-6">
			<div class="btn-group btn-group-justified">
				<a href="{{ action('UserController@create') }}" class="btn btn-primary"><span class="fa fa-user-plus"></span> Add User</a>
				<div class="btn-group">
				  	<button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
					@if($role == '3' && $inactive == false)
						Students
					@elseif($role == '3' && $inactive == true)
						Inactive
					@elseif($role == '2')
						Teachers
					@else
						Admins
					@endif
					<span class="caret"></span>
				  	</button>
				  	<ul class="dropdown-menu dropdown-menu-right">
				    	<li @if(($role == '3') && ($inactive == false)) class="active" @endif><a href="?role=3">Students</a></li>
				    	<li @if(($role == '3') && ($inactive == true)) class="active" @endif><a href="?role=3&inactive=1">Inactive</a></li>
				    	<li @if($role == '2') class="active" @endif><a href="?role=2">Teachers</a></li>
				    	<li @if($role == '1') class="active" @endif><a href="?role=1">Admins</a></li>
				  	</ul>
				</div>
			</div>
		</div>
	</div>
@stop

@section('contents')
<div class="row">
	<div class="col-md-12">
		<div class="table-responsive">
			<table id="user-list" class="table table-hover table-striped">
				<thead>
					<tr>
						<th>Ref. Id</th>
						<th>Avatar</th>
						<th>Name</th>
						<th>Age</th>
						<th>Phone</th>
						<th>Classes</th>
						<th>Remarks</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@forelse($users as $user)
						<tr>
							<td>{{ $user->ref_id }}</td>
							<td class="td-thumbnail">
							@if(isset($user->avatar) && $user->avatar != '')
							<img src="{{ asset('img/avatar/'.$user->avatar) }}" class="img-thumbnail">
							@endif
							</td>
							<td>{{ $user->name }}</td>
							<td>{{ $user->age }}</td>
							<td>{{ $user->phone }}</td>
							<td><a href="{{ action('UserController@editSchedules', array($user->id)) }}">
								<?php 
								$id = $user->id;
								$appointments = $user->appointments->groupBy('schedule_id');
								$miss = $user->appointments->filter(function($a) use ($id){
									return $a->attendance->filter(function($attend) use ($id){
										return (($attend->student_id == $id) && ($attend->attend == 0));
									})->count();
								})->groupBy('schedule_id');
								?>
								@forelse($user->schedules as $s)
									<?php $a = ((isset($appointments[$s->id]) ? count($appointments[$s->id]) : 0)+$s->pivot->used_session) - min(isset($miss[$s->id]) ? count($miss[$s->id]) : 0, $s->pivot->miss_count); ?>
									{{ $s->name }} [{{ $a }}/{{ $s->pivot->total_session }}({{ min(isset($miss[$s->id]) ? count($miss[$s->id]) : 0, $s->pivot->miss_count) }})]<br>
								@empty
									-
								@endforelse
								{{-- $user->schedules->count() --}}
							</a></td>
							<td>{{ $user->remarks }}</td>
							<td class="td-delete">
								<a href="{{ route('users.show', array($user->id)) }}" class="btn btn-primary"><i class="fa fa-eye"></i></a>
								<a class="btn btn-warning" href="{{ action('UserController@edit', array($user->id)) }}"><i class="fa fa-pencil"></i></a>
								{{ Form::open(array('action' => array('UserController@destroy', $user->id), 'method' => 'delete')) }}
									<button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
								{{ Form::close() }}
							</td>
						</tr>
					@empty
						<tr>
							<td colspan="9">No user found.</td>
						</tr>
					@endforelse
				</tbody>
				<tfoot>
					<tr>
						<td>Ref. Id</td>
						<td>Avatar</td>
						<td>Name</td>
						<td>Age</td>
						<td>Phone</td>
						<td>Classes</td>
						<td>Remarks</td>
						<td>Actions</td>
					</tr>
				</tfoot>
			</table>
		</div>
		{{ $users->appends(array('role' => $role))->links() }}
	</div>
</div>
@stop