app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
 */

Route::group(array('before' => 'auth'), function () {

	Route::group(array('prefix' => 'users'), function(){

		Route::get('/search', 'UserController@search');
		Route::get('/{users}/edit/schedules', 'UserController@editSchedules');
		Route::post('/{users}/edit/schedules', 'UserController@createSchedules');
		Route::post('/{users}/edit/schedules/{sid}', 'UserController@updateSchedules');
		Route::delete('/{users}/edit/schedules/{sid}/destroy', 'UserController@destroySchedules');

		Route::get('/{users}/edit/appointments/{sid?}', 'UserController@editAppointments');
		Route::delete('/{users}/edit/appointments/{sid?}/destroy', 'UserController@destroyAppointments');
		Route::get('/{users}/show/appointments/{sid?}', 'UserController@showAppointments');
		
		Route::get('/{users}/show/assessments/{sid?}', 'UserController@showAssessments');

	});

	Route::resource('users', 'UserController');

	Route::get('attachments/{id}/destroy', 'AttachmentController@destroy');
	Route::get('attachments/{id}/destroyUrl', 'AttachmentController@destroyUrl');
	Route::resource('attachments', 'AttachmentController', array('only' => array('show')));

	Route::post('courses/{id}/edit/lessons/reorder', 'SyllabusController@reorder');
	Route::resource('courses/{id}/edit/lessons', 'SyllabusController', array('except' => array('show', 'create', 'edit')));
	Route::get('courses/{id}/edit/exam', 'SyllabusController@exam');
	Route::get('courses/{id}/lessons', array(
		'as' => 'courses.show.lessons', 
		'uses' => 'CourseController@show'
	));
	Route::get('courses/{id}/exams', array(
		'as' => 'courses.show.exam', 
		'uses' => 'CourseController@exam'
	));
	Route::resource('courses', 'CourseController');

	Route::get('schedules/{id}/edit/students', 'ScheduleController@editStudents');
	Route::resource('schedules', 'ScheduleController', array('except' => array('show')));

	Route::get('appointment/list/{year?}/{month?}/{day?}', 'AppointmentController@listIndex');
	Route::get('appointment/exam/{year?}/{month?}', 'AppointmentController@listExam');
	Route::get('appointment/events/{sid?}', 'AppointmentController@getEvents');
	Route::post('appointment/events/add', 'AppointmentController@addEventStudent');
	Route::post('appointment/events/delete', 'AppointmentController@deleteEventStudent');

	Route::get('appointment/{id}/students', 'AppointmentController@getStudents');
	Route::post('appointment/{id}/students', 'AppointmentController@addStudent');
	Route::post('appointment/{id}/students/delete', 'AppointmentController@deleteStudent');

	Route::get('appointment/{id}/lessons', 'AppointmentController@getLesson');
	Route::post('appointment/{id}/lessons', array(
		'as' => 'appointment.lesson.add', 
		'uses' => 'AppointmentController@addLesson'
	));
	Route::post('appointment/{id}/lessons/delete', array(
		'as' => 'appointment.lesson.delete', 
		'uses' => 'AppointmentController@deleteLesson'
	));
	Route::post('appointment/{id}/lessons/auto', array(
		'as' => 'appointment.lesson.choose', 
		'uses' => 'AppointmentController@chooseAuto'
	));
	/*Route::post('appointment/{id}/lessons/auto', array(
		'as' => 'appointment.lesson.auto', 
		'uses' => 'AppointmentController@toggleAuto'
	));*/

	Route::get('appointment/{id}/attendance', 'AppointmentController@getAttend');
	Route::post('appointment/{id}/attendance/update', array(
		'as' => 'appointment.attend.update', 
		'uses' => 'AppointmentController@updateAttend')
	);

	Route::get('appointment/{id}/remarks', 'AppointmentController@getRemarks');
	Route::post('appointment/{id}/remarks/update', array(
		'as' => 'appointment.remarks.update', 
		'uses' => 'AppointmentController@updateRemarks')
	);
	Route::resource('appointment', 'AppointmentController');

	Route::get('reports/{uid}/{sid}', 'ReportController@getReport');

	Route::resource('setting/notification', 'Setting\\NotificationController', array('except' => array('show')));
	Route::controller('setting', 'SettingController');

	Route::controller('dashboard', 'HomeController');

	Route::controller('mbti', 'PsychologyTestController');

	Route::get('/', 'HomeController@getIndex');

});

/*
Route::group(array('prefix' => 'demo'), function(){

	Route::get('/assessment', function(){
		$data['questions'] = Config::get('question.ver2');
		$data['assets_version'] = 2;

		return View::make('demo.assessment', $data);
	});

	Route::get('/history', function(){
		$data['questions'] = Config::get('question.ver2');
		$data['assets_version'] = 2;

		return View::make('demo.history', $data);
	});

});*/

/*Route::get('update', function(){
	Artisan::call('migrate', array('--force' => true));
});*/

//Route::controller('/utility', 'DevController');

Route::controller('/', 'AuthController');

app/models/Schedule.php
<?php

class Schedule extends Eloquent {

	use SoftDeletingTrait;

	protected $table = 'schedules';

	protected $fillable = array('course_id');

	protected $guarded = array('id');

	protected $dates = array('deleted_at');

	protected $appends = array('name');

	public function getNameAttribute() {
		$tutor = $this->tutors()->first();
		//$tutorname = $tutor ? '/' . $tutor->name : '/(No Tutor)';

		$course = $this->course;
		$coursename = isset($course->name) ? $course->name : '(Course Deleted)';

		return $this->attributes['id'] . ". " . $coursename;
	}

	public function appointments(){
		return $this->hasMany('Appointment', 'schedule_id', 'id');
	}

	public function course() {
		return $this->belongsTo('Course', 'course_id', 'id');
	}

	public function times() {
		return $this->hasMany('ScheduleTime', 'schedule_id', 'id');
	}

	public function tutors() {
		return $this->belongsToMany('User', 'schedules_tutors', 'schedule_id', 'user_id');
	}

	public function students() {
		return $this->belongsToMany('User', 'schedules_students', 'schedule_id', 'user_id')->withPivot('start_date', 'expiry_date', 'total_session', 'used_session', 'exam', 'used_exam', 'miss_count', 'deleted_at', 'id')->withTimestamps();
	}

}

app/controllers/ScheduleController.php
<?php

class ScheduleController extends \BaseController {

	protected $layout = "layout";

	public function __construct() {
		parent::__construct();
		$this->data['active'] = 'schedule';

		$this->beforeFilter('@onlyAdmin', array('except' => array('index', 'editStudents')));
	}

	public function onlyAdmin($route, $request){
		$role = $this->data['cu']->role;

		if($role > 1) return Redirect::action('ScheduleController@index');
	}

	public function index() {
		if($this->data['cu']->role <= 1)
			$this->data['schedules'] = Schedule::all()->load('course');
		else 
			$this->data['schedules'] = $this->data['cu']->schedules->load('course');

		$this->layout->with($this->data);
		$this->layout->content = View::make('schedule.index', $this->data);
	}

	public function create() {
		$this->data['course'] = Course::lists('name', 'id');
		$this->data['tutors'] = User::whereIn('role', array(1,2))->lists('name', 'id');
		$this->data['tutors'][-1] = "None";
		ksort($this->data['tutors']);
		$this->data['days'] = array(0 => 'Sun', 1 => 'Mon', 2 => 'Tues', 3 => 'Wed', 4 => 'Thurs', 5 => 'Fri', 6 => 'Sat');

		$this->layout->with($this->data);
		$this->layout->content = View::make('schedule.form', $this->data);
	}

	public function store() {
		$courses = implode(Course::lists('id'), ',');
		$rules = array('course' => 'required|in:'.$courses);

		$tutors = array();
		foreach(Input::get('tutors') as $key=>$value){
			if($value > 0) {
				$rules['tutors.'.$key] = 'exists:users,id';
				$tutors[] = $value;
			}
		}
		$validation = Validator::make(Input::all(), $rules);

		if ($validation->fails()) {
			return Redirect::action('ScheduleController@create')->withInput(Input::except('day', 'shour', 'smin', 'ehour', 'emin'))->withErrors($validation)->with('msg_error', 'There are some errors in your form.');
		} else {
			$day = Input::get('day');
			$times = array();
			if (is_array($day)) {
				foreach ($day as $key => $value) {
					$input = array(
						'day' => Input::get('day.' . $key),
						'shour' => Input::get('shour.' . $key),
						'smin' => Input::get('smin.' . $key),
						'ehour' => Input::get('ehour.' . $key),
						'emin' => Input::get('emin.' . $key),
					);
					$validate = Validator::make($input, array(
						'day' => 'required_with:shour,smin,ehour,emin',
						'shour' => 'required_with:day,smin,ehour,emin',
						'smin' => 'required_with:day,shour,ehour,emin',
						'ehour' => 'required_with:day,shour,smin,emin',
						'emin' => 'required_with:day,shour,smin,ehour',
					));

					if ($validate->fails()) {
						return Redirect::action('ScheduleController@create')->withInput(Input::except('day', 'shour', 'smin', 'ehour', 'emin'))->withErrors($validation)->with('msg_error', 'There are some errors in your form.');
					} else {
						$times[] = ScheduleTime::create($input); //@TODO: order?
					}
				}
			}

			$schedule = Schedule::create(array('course_id' => Input::get('course')));
			DB::transaction(function () use ($times, $schedule, $tutors) {
				$schedule->tutors()->sync($tutors);
			});

			return Redirect::action('ScheduleController@create')->with('msg_success', 'You\'ve created a new schedule. View it\'s info <a href="' . action('ScheduleController@edit', array($schedule->id)) . '">here</a>.');
		}
	}

	public function show($id) {

	}

	public function edit($id) {
		$this->data['schedule'] = Schedule::findOrFail($id)->load('course');
		$this->data['tabs'] = array('students' => $this->data['schedule']->students->count());
		$this->data['course'] = Course::lists('name', 'id');
		$this->data['tutors'] = User::whereIn('role', array(1,2))->lists('name', 'id');
		$this->data['tutors'][-1] = "None";
		ksort($this->data['tutors']);
		$this->data['days'] = array(0 => 'Sun', 1 => 'Mon', 2 => 'Tues', 3 => 'Wed', 4 => 'Thurs', 5 => 'Fri', 6 => 'Sat');

		$this->layout->with($this->data);
		$this->layout->content = View::make('schedule.form', $this->data);
	}

	public function editStudents($id){
		$this->data['schedule'] = Schedule::findOrFail($id);
		$this->data['tabs'] = array('students' => $this->data['schedule']->students->count());
		$this->data['users'] = $this->data['schedule']->students()->orderBy('name', 'asc')->paginate(50);

		$this->layout->with($this->data);
		$this->layout->content = View::make('schedule.student', $this->data);	
	}

	public function update($id) {
		$courses = implode(Course::lists('id'), ',');
		$rules = array('course' => 'required|in:'.$courses);
		$tutors = array();
		foreach(Input::get('tutors') as $key=>$value){
			if($value > 0) {
				$rules['tutors.'.$key] = 'exists:users,id';
				$tutors[] = $value;
			}
		}
		$validation = Validator::make(Input::all(), $rules);

		if ($validation->fails()) {
			return Redirect::action('ScheduleController@edit', array($id))->withInput(Input::except('day', 'shour', 'smin', 'ehour', 'emin'))->withErrors($validation)->with('msg_error', 'There are some errors in your form.');
		} else {
			$day = Input::get('day');
			$times = array();
			if (is_array($day)) {
				foreach ($day as $key => $value) {
					$input = array(
						'day' => Input::get('day.' . $key),
						'shour' => Input::get('shour.' . $key),
						'smin' => Input::get('smin.' . $key),
						'ehour' => Input::get('ehour.' . $key),
						'emin' => Input::get('emin.' . $key),
					);
					$validate = Validator::make($input, array(
						'day' => 'required_with:shour,smin,ehour,emin',
						'shour' => 'required_with:day,smin,ehour,emin',
						'smin' => 'required_with:day,shour,ehour,emin',
						'ehour' => 'required_with:day,shour,smin,emin',
						'emin' => 'required_with:day,shour,smin,ehour',
					));

					if ($validate->fails()) {
						return Redirect::action('ScheduleController@edit', array($id))->withInput(Input::except('day', 'shour', 'smin', 'ehour', 'emin'))->withErrors($validation)->with('msg_error', 'There are some errors in your form.');
					} else {
						$times[] = ScheduleTime::create($input);
					}
				}
			}

			$schedule = Schedule::findOrFail($id);
			$schedule->course_id = Input::get('course');
			$schedule->save();
			DB::transaction(function () use ($times, $schedule, $tutors) {
				//$schedule->tutors()->detach();
				//$schedule->tutors()->attach(array(Input::get('tutors')));
				//$schedule->times()->delete();
				//$schedule->times()->saveMany($times);
				$schedule->tutors()->sync($tutors);
			});

			return Redirect::action('ScheduleController@edit', array($id))->with('msg_success', 'You\'ve updated schedule successfully.');
		}
	}

	public function destroy($id) {
		Schedule::findOrFail($id)->delete();

		return Redirect::action('ScheduleController@index')->with('msg_success', 'Schedule deleted successfully.');
	}

}

app/views/schedule/form.blade.php
@extends('layout')

@section('breadcrumb')
	<li><a href="{{ action('ScheduleController@index') }}">Class Management</a></li>
	<li class="active">
	@if(isset($schedule))
	Edit Class
	@else
	Add Class
	@endif
	</li>
@stop

@section('page_title')
	@if(isset($schedule))
	<h1>Edit Class</h1>
	@else
	<h1>Add Class</h1>
	@endif
@stop

@section('page_action')
@if(isset($schedule))
{{ Form::open(array('action' => array('ScheduleController@destroy', $schedule->id), 'method' => 'delete')) }}
	<button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
{{ Form::close() }}
@endif
@stop

@section('footer_js')
<script type="text/javascript">
$().ready(function(){

	var input_schedule_time = '<div>\
					{{ Form::select('day[]', $days, null, array('class' => 'form-control')) }}\
					{{ Form::text('shour[]', null, array('class' => 'form-control')) }}\
					{{ Form::text('smin[]', null, array('class' => 'form-control')) }}\
					<span>Until</span>\
					{{ Form::text('ehour[]', null, array('class' => 'form-control')) }}\
					{{ Form::text('emin[]', null, array('class' => 'form-control')) }}\
					<a class="btn btn-warning remove"><span class="glyphicon glyphicon-minus"></span></a>\
				</div>';

	$('#input-schedule-add').click(function(){
		$('#input-schedule-times').append(input_schedule_time);
	});

	$('#input-schedule').on('click', '.remove', function(){
		$(this).parent().remove();
	});
});
</script>
@stop

@section('contents')
@if(isset($schedule))
<div class="row">
	<div class="col-md-12">
		<ul class="nav nav-tabs">
		  	<li class="active" role="presentation">
		  		<a href="{{ route('schedules.edit', array($schedule->id)) }}">General Info</a>
		  	</li>
		  	<li role="presentation">
		  		<a href="{{ action('ScheduleController@editStudents', array($schedule->id)) }}">Students <span class="badge">{{ $tabs['students'] or 0 }}</span></a>
		  	</li>
		</ul>
	</div>
</div>
@endif
<div class="row">
	<div class="col-md-6">
		@if(count($course) == 0)
			<div class="alert alert-warning" role="alert">
				You haven't created any course. Please create a new course <a href="{{ action('CourseController@create') }}">here</a>.
			</div>
		@else
		@if(isset($schedule))
			{{ Form::model($schedule, array(
				'action' => array('ScheduleController@update',$schedule->id),
				'method' => 'put'
			)) }}
		@else
			{{ Form::open(array('action' => 'ScheduleController@store')) }}
		@endif
			<div class="form-group {{ hasError($errors, 'course') }}">
				<label for="name">*Course (Changing course may cause problems for existing student)</label>
				@if(!isset($schedule->course))
				(Original course deleted.)
				@endif
				{{ Form::select('course', $course, isset($schedule->course) ? $schedule->course->id : null, array('class' => 'form-control')) }}
				{{ errorBlock($errors, 'course') }}
			</div>
			<label for="tutor">*Teacher</label>
			<?php $i = 0; ?>
			@if(isset($schedule))
			<?php $schedule->tutors->each(function($tutor) use ($tutors, $errors, &$i){ ?>
			<div class="form-group {{ hasError($errors, 'tutors.'.$i) }}">
				{{ Form::select('tutors['.$i.']', $tutors, $tutor->id, array('class' => 'form-control')) }}
				{{ errorBlock($errors, 'tutors.'.$i) }}
			</div>
			<?php $i++; }); ?>
			@endif
			@for($j = $i; $j < $i+3; $j++)
			<div class="form-group {{ hasError($errors, 'tutors.'.$j) }}">
				{{ Form::select('tutors['.$j.']', $tutors, null, array('class' => 'form-control')) }}
				{{ errorBlock($errors, 'tutors.'.$j) }}
			</div>
			@endfor
			<!--<div id="input-schedule" class="form-group">
				<label for="schedule">Time Schedule(24 hour format)</label>
				@if(isset($schedule))
					{{--@foreach($schedule->times()->orderBy('day')->get() as $time)
						<div>
							{{ Form::select('day[]', $days, $time->day, array('class' => 'form-control')) }}
							{{ Form::text('shour[]', $time->shour, array('class' => 'form-control')) }}
							{{ Form::text('smin[]', $time->smin, array('class' => 'form-control')) }}
							<span>Until</span>
							{{ Form::text('ehour[]', $time->ehour, array('class' => 'form-control')) }}
							{{ Form::text('emin[]', $time->emin, array('class' => 'form-control')) }}
							<a class="btn btn-warning remove"><span class="glyphicon glyphicon-minus"></span></a>
						</div>
					@endforeach--}}
				@endif
				<div id="input-schedule-times"></div>
				<div>
					<a class="btn btn-warning" id="input-schedule-add"><span class="glyphicon glyphicon-plus"></span></a>
				</div>
			</div>-->
			<div class="form-group">
				@if(isset($schedule))
				<input type="submit" value="Update Class Info" class="btn btn-primary btn-block">
				@else
				<input type="submit" value="Create New Class" class="btn btn-primary btn-block">
				@endif
			</div>
		{{ Form::close() }}
	</div>
</div>
@endif
@stop

app/views/schedule/index.blade.php
@extends('layout')

@section('breadcrumb')
	<li><a href="{{ action('ScheduleController@index') }}">Class Management</a></li>
@stop

@section('page_title')
	<h1>Class Management</h1>
	<h2>Manage teachers, students and materials for classes.</h2>
@stop

@section('page_action')
@if($cu->role <= 1)
	<a href="{{ action('ScheduleController@create') }}" class="btn btn-primary"><span class="fa fa-plus"></span> Add Class</a>
@endif
@stop

@section('header_css')
	<link rel="stylesheet" href="{{ asset('css/schedule.css') }}">
@stop

@section('contents')
	<div class="row">
		<div class="col-md-12">
			<div class="table-responsive">
				<table id="schedule-list" class="table table-hover table-striped">
					<thead>
						<tr>
							<th>Id</th>
							<th>Course Title</th>
							<th>Tutors</th>
							<th>Students</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						@forelse($schedules as $schedule)
							<tr>
								<td>{{ $schedule->id }}</td>
								<td>
									@if(isset($schedule->course))
									<a href="{{ route('courses.show', array($schedule->course->id)) }}">{{ $schedule->course->name }}</a>
									@else
										Course Deleted
									@endif
								</td>
								<td>
									@foreach($schedule->tutors as $tutor)
										<a href="{{ action('UserController@edit', array($tutor->id)) }}">{{ $tutor->name }}</a><br>
									@endforeach
								</td>
								<td><a href="{{ action('ScheduleController@editStudents', array($schedule->id)) }}">{{ $schedule->students()->count() }}</a></td>
								<td class="td-delete">
								@if($cu->role <= 1)
									<a class="btn btn-warning" href="{{ action('ScheduleController@edit', array($schedule->id)) }}"><i class="fa fa-pencil"></i></a>
									{{ Form::open(array('action' => array('ScheduleController@destroy', $schedule->id), 'method' => 'delete')) }}
										<button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
									{{ Form::close() }}
								@elseif($cu->role == 2)
									<a class="btn btn-primary" href="{{ action('ScheduleController@editStudents', array($schedule->id)) }}"><i class="fa fa-eye"></i> View Students </a>
								@endif
								</td>
							</tr>
						@empty
							<tr>
								<td colspan="5">No schedule found.</td>
							</tr>
						@endforelse
					</tbody>
					<tfoot>
						<tr>
							<td>Id</td>
							<td>Course Title</td>
							<td>Tutors</td>
							<td>Students</td>
							<td>Actions</td>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</div>
@stop

app/views/schedule/student.blade.php
@extends('layout')

@section('breadcrumb')
	<li><a href="{{ action('ScheduleController@index') }}">Class Management</a></li>
	<li class="active">
	@if(isset($schedule))
	Edit Class
	@else
	Add Class
	@endif
	</li>
@stop

@section('page_title')
	<h1>Edit Class Students</h1>
@stop

@section('page_action')
@if(isset($schedule) && ($cu->role <= 1))
{{ Form::open(array('action' => array('ScheduleController@destroy', $schedule->id), 'method' => 'delete')) }}
	<button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
{{ Form::close() }}
@endif
@stop

@section('contents')
@if(isset($schedule) && ($cu->role <= 1))
<div class="row">
	<div class="col-md-12">
		<ul class="nav nav-tabs">
		  	<li role="presentation">
		  		<a href="{{ route('schedules.edit', array($schedule->id)) }}">General Info</a>
		  	</li>
		  	<li class="active" role="presentation">
		  		<a href="{{ action('ScheduleController@editStudents', array($schedule->id)) }}">Students <span class="badge">{{ $tabs ['students'] or 0 }}</span></a>
		  	</li>
		</ul>
	</div>
</div>
@endif
<div class="row">
	<div class="col-md-12">
		<div class="table-responsive">
			<table id="user-list" class="table table-hover table-striped">
				<thead>
					<tr>
						<th>Ref. Id</th>
						<th>Avatar</th>
						<th>Name</th>
						<th>Age</th>
						<th>Phone</th>
						<th>Progress</th>
						<th>Remarks</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@forelse($users as $user)
						<tr>
							<td>{{ $user->ref_id }}</td>
							<td class="td-thumbnail">
							@if(isset($user->avatar) && $user->avatar != '')
							<img src="{{ asset('img/avatar/'.$user->avatar) }}" class="img-thumbnail">
							@endif
							</td>
							<td>{{ $user->name }}</td>
							<td>{{ $user->age }}</td>
							<td>{{ $user->phone }}</td>
							<td>
								<?php 
								$id = $user->id;
								$appointments = $user->appointments->groupBy('schedule_id');
								$miss = $user->appointments->filter(function($a) use ($id){
									return $a->attendance->filter(function($attend) use ($id){
										return (($attend->student_id == $id) && ($attend->attend == 0));
									})->count();
								})->groupBy('schedule_id');
								?>
								@forelse($user->schedules as $s)
									@if($s->id == $schedule->id)
									<?php $a = ((isset($appointments[$s->id]) ? count($appointments[$s->id]) : 0)+$s->pivot->used_session) - min(isset($miss[$s->id]) ? count($miss[$s->id]) : 0, $s->pivot->miss_count); ?>
									 {{ $a }}/{{ $s->pivot->total_session }}<br>
									@endif
								@empty
									0
								@endforelse
							</td>
							<td class="td-remarks">{{ $user->remarks }}</td>
							<td class="td-delete">
								<a href="{{ route('users.show', array($user->id)) }}" class="btn btn-primary"><i class="fa fa-eye"></i> View</a>
								@if($cu->role <= 1)
								<a class="btn btn-warning" href="{{ action('UserController@edit', array($user->id)) }}"><i class="fa fa-pencil"></i> Edit</a>
								@endif
							</td>
						</tr>
					@empty
						<tr>
							<td colspan="9">No user found.</td>
						</tr>
					@endforelse
				</tbody>
				<tfoot>
					<tr>
						<td>Ref. Id</td>
						<td>Avatar</td>
						<td>Name</td>
						<td>Age</td>
						<td>Phone</td>
						<td>Schedule</td>
						<td>Remarks</td>
						<td>Actions</td>
					</tr>
				</tfoot>
			</table>
		</div>
		{{ $users->links() }}
	</div>
</div>
@stop