app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
 */

Route::group(array('before' => 'auth'), function () {

	Route::group(array('prefix' => 'users'), function(){

		Route::get('/search', 'UserController@search');
		Route::get('/{users}/edit/schedules', 'UserController@editSchedules');
		Route::post('/{users}/edit/schedules', 'UserController@createSchedules');
		Route::post('/{users}/edit/schedules/{sid}', 'UserController@updateSchedules');
		Route::delete('/{users}/edit/schedules/{sid}/destroy', 'UserController@destroySchedules');

		Route::get('/{users}/edit/appointments/{sid?}', 'UserController@editAppointments');
		Route::delete('/{users}/edit/appointments/{sid?}/destroy', 'UserController@destroyAppointments');
		Route::get('/{users}/show/appointments/{sid?}', 'UserController@showAppointments');
		
		Route::get('/{users}/show/assessments/{sid?}', 'UserController@showAssessments');

	});

	Route::resource('users', 'UserController');

	Route::get('attachments/{id}/destroy', 'AttachmentController@destroy');
	Route::get('attachments/{id}/destroyUrl', 'AttachmentController@destroyUrl');
	Route::resource('attachments', 'AttachmentController', array('only' => array('show')));

	Route::post('courses/{id}/edit/lessons/reorder', 'SyllabusController@reorder');
	Route::resource('courses/{id}/edit/lessons', 'SyllabusController', array('except' => array('show', 'create', 'edit')));
	Route::get('courses/{id}/edit/exam', 'SyllabusController@exam');
	Route::get('courses/{id}/lessons', array(
		'as' => 'courses.show.lessons', 
		'uses' => 'CourseController@show'
	));
	Route::get('courses/{id}/exams', array(
		'as' => 'courses.show.exam', 
		'uses' => 'CourseController@exam'
	));
	Route::resource('courses', 'CourseController');

	Route::get('schedules/{id}/edit/students', 'ScheduleController@editStudents');
	Route::resource('schedules', 'ScheduleController', array('except' => array('show')));

	Route::get('appointment/list/{year?}/{month?}/{day?}', 'AppointmentController@listIndex');
	Route::get('appointment/exam/{year?}/{month?}', 'AppointmentController@listExam');
	Route::get('appointment/events/{sid?}', 'AppointmentController@getEvents');
	Route::post('appointment/events/add', 'AppointmentController@addEventStudent');
	Route::post('appointment/events/delete', 'AppointmentController@deleteEventStudent');

	Route::get('appointment/{id}/students', 'AppointmentController@getStudents');
	Route::post('appointment/{id}/students', 'AppointmentController@addStudent');
	Route::post('appointment/{id}/students/delete', 'AppointmentController@deleteStudent');

	Route::get('appointment/{id}/lessons', 'AppointmentController@getLesson');
	Route::post('appointment/{id}/lessons', array(
		'as' => 'appointment.lesson.add', 
		'uses' => 'AppointmentController@addLesson'
	));
	Route::post('appointment/{id}/lessons/delete', array(
		'as' => 'appointment.lesson.delete', 
		'uses' => 'AppointmentController@deleteLesson'
	));
	Route::post('appointment/{id}/lessons/auto', array(
		'as' => 'appointment.lesson.choose', 
		'uses' => 'AppointmentController@chooseAuto'
	));
	/*Route::post('appointment/{id}/lessons/auto', array(
		'as' => 'appointment.lesson.auto', 
		'uses' => 'AppointmentController@toggleAuto'
	));*/

	Route::get('appointment/{id}/attendance', 'AppointmentController@getAttend');
	Route::post('appointment/{id}/attendance/update', array(
		'as' => 'appointment.attend.update', 
		'uses' => 'AppointmentController@updateAttend')
	);

	Route::get('appointment/{id}/remarks', 'AppointmentController@getRemarks');
	Route::post('appointment/{id}/remarks/update', array(
		'as' => 'appointment.remarks.update', 
		'uses' => 'AppointmentController@updateRemarks')
	);
	Route::resource('appointment', 'AppointmentController');

	Route::get('reports/{uid}/{sid}', 'ReportController@getReport');

	Route::resource('setting/notification', 'Setting\\NotificationController', array('except' => array('show')));
	Route::controller('setting', 'SettingController');

	Route::controller('dashboard', 'HomeController');

	Route::controller('mbti', 'PsychologyTestController');

	Route::get('/', 'HomeController@getIndex');

});

/*
Route::group(array('prefix' => 'demo'), function(){

	Route::get('/assessment', function(){
		$data['questions'] = Config::get('question.ver2');
		$data['assets_version'] = 2;

		return View::make('demo.assessment', $data);
	});

	Route::get('/history', function(){
		$data['questions'] = Config::get('question.ver2');
		$data['assets_version'] = 2;

		return View::make('demo.history', $data);
	});

});*/

/*Route::get('update', function(){
	Artisan::call('migrate', array('--force' => true));
});*/

//Route::controller('/utility', 'DevController');

Route::controller('/', 'AuthController');

app/views/courses/form.blade.php
@extends('layout')

@section('breadcrumb')
	<li><a href="{{ action('CourseController@index') }}">Course Management</a></li>
	<li class="active">
	@if(isset($course))
	Edit Course
	@else
	Add Course
	@endif
	</li>
@stop

@section('page_title')
	@if(isset($course))
	<h1>Edit Course</h1>
	@else
	<h1>Add Course</h1>
	@endif
@stop

@section('page_action')
@if(isset($course))
	<a href="{{ route('courses.show', array($course->id)) }}" class="btn btn-primary"><i class="fa fa-eye"></i> View</a>
	{{ Form::open(array('action' => array('CourseController@destroy', $course->id), 'method' => 'delete', 'class' => 'form-ib')) }}
		<button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
	{{ Form::close() }}
@endif
@stop

@section('contents')
@if(isset($course))
<div class="row">
	<div class="col-md-12">
		<ul class="nav nav-tabs">
		  	<li role="presentation" class="active"><a href="{{ action('CourseController@edit', array($id)) }}">General Info</a></li>
		  	<li role="presentation"><a href="{{ action('SyllabusController@index', array($id)) }}">Lessons <span class="badge">{{ @$tab_count['syllabus'] }}</span></a></li>
		  	<li role="presentation"><a href="{{ action('SyllabusController@exam', array($id)) }}">Exams <span class="badge">{{ @$tab_count['exam'] }}</span></a></li>
		</ul>
	</div>
</div>
@endif
<div class="row">
	<div class="col-md-6">
		@if(isset($course))
			{{ Form::model($course, array(
				'action' => array('CourseController@update',$course->id),
				'files' => true,
				'method' => 'put'
			)) }}
		@else
			{{ Form::open(array('action' => 'CourseController@store', 'files' => true)) }}
		@endif
			<div class="form-group {{ hasError($errors, 'name') }}">
				<label for="name">*Title</label>
				{{ Form::text('name', null, array('class' => 'form-control')) }}
				{{ errorBlock($errors, 'name') }}
			</div>
			<div class="form-group">
				<label for="description">Description</label>
				{{ Form::textarea('description', null, array('class' => 'form-control', 'row' => 8)) }}
			</div>
			<div class="form-group">
				@if(isset($course))
				<input type="submit" value="Update Course Info" class="btn btn-primary btn-block">
				@else
				<input type="submit" value="Create New Course" class="btn btn-primary btn-block">
				@endif
			</div>
		{{ Form::close() }}
	</div>
</div>
@stop

app/views/courses/index.blade.php
@extends('layout')

@section('breadcrumb')
	@if(isset($search) && $search == true)
	<li><a href="{{ action('CourseController@index') }}">Course Management</a></li>
	<li>Search</li>
	@else
	<li class="active"><a href="{{ action('CourseController@index') }}">Course Management</a></li>
	@endif
@stop

@section('page_title')
@if($cu->role >= 2)
	<h1>My Courses</h1>
	<h2>Browse materials of courses you've attended. </h2>
@else
	<h1>Course Management</h1>
	<h2>Create and edit materials of your courses.</h2>
@endif
@stop

@section('page_action')
@if($cu->role <= 1)
	<a href="{{ action('CourseController@create') }}" class="btn btn-primary"><span class="fa fa-plus"></span> Add Course</a>
@endif
@stop

@section('footer_js')
	@if($cu->role == 3)
	<script type="text/javascript">
		var nextTour = '{{ action('AppointmentController@index') }}?tour=1';
	</script>
	<script type="text/javascript" src="{{ asset('js/tours/courses.js') }}"></script>
	@endif
@stop

@section('contents')
<div class="row">
	<div class="col-md-12">
		<div class="table-responsive">
			<table id="course-list" class="table table-hover table-striped">
				<thead>
					<tr>
						<th>Id</th>
						<th>Title</th>
						<th>Description</th>
						@if($cu->role <= 2)
						<th>Lessons</th>
						<th>Exams</th>
						<th>Attachments</th>
						@endif
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@forelse($courses as $course)
						<tr>
							<td>{{ $course->id }}</td>
							<td>{{ $course->name }}</td>
							<td>{{ $course->description }}</td>
							@if($cu->role <= 2)
							<td>
								@if($cu->role <= 1)
								<a href="{{ action('SyllabusController@index', array($course->id)) }}">
								{{ $course->syllabus()->where('is_exam', '=', false)->count() }}</a>
								@else
								{{ $course->syllabus()->where('is_exam', '=', false)->count() }}
								@endif
							</td>
							<td>
								@if($cu->role <= 1)
								<a href="{{ action('SyllabusController@exam', array($course->id)) }}">{{ $course->syllabus()->where('is_exam', '=', true)->count() }}</a>
								@else
								{{ $course->syllabus()->where('is_exam', '=', true)->count() }}
								@endif
							</td>
							<td>{{ $course->attachment()->count() }}</td>
							@endif
							<td class="td-delete">
								<a href="{{ route('courses.show', array($course->id)) }}" class="btn btn-primary"><i class="fa fa-eye"></i></a>
								@if($cu->role <= 1)
								<a href="{{ action('CourseController@edit', array($course->id)) }}" class="btn btn-warning"><i class="fa fa-pencil"></i></a>
								{{ Form::open(array('action' => array('CourseController@destroy', $course->id), 'method' => 'delete')) }}
									<button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
								{{ Form::close() }}
								@endif
							</td>
						</tr>
					@empty
						<tr>
							<td colspan="7">No course found.</td>
						</tr>
					@endforelse
				</tbody>
				<tfoot>
					<tr>
						<td>Id</td>
						<td>Title</td>
						<td>Description</td>
						@if($cu->role <= 2)
						<td>Lessons</td>
						<td>Exams</td>
						<td>Attachments</td>
						@endif
						<td>Actions</td>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>
@stop

app/views/courses/panel.blade.php
<div class="panel panel-default">
	<div class="panel-heading">
		<h4 class="panel-title">
			<span href="#syllabus-{{ $syllabus->id }}" data-toggle="collapse">{{ $syllabus->name }}</span>
			@if(isset($new) && $new)
			<span class="badge">New</span>
			@endif
		</h4>
	</div>
	<div id="syllabus-{{ $syllabus->id }}" class="panel-collapse @if(isset($collapse)) collapse @endif">
		<div class="panel-body">
			<pre>{{ $syllabus->description }}</pre>
			@if($syllabus->attachurl()->count() > 0)
			@foreach($syllabus->attachurl as $attachurl)
				<i class="fa fa-link"></i> 
				<a href="{{ $attachurl->url }}" target="_blank">{{ $attachurl->url }}</a> 
				<br>
			@endforeach
			@endif
			@if($syllabus->attachment()->count() > 0)
			@foreach($syllabus->attachment as $attachment)
			<p>
				<i class="fa @if($attachment->mime == "application/pdf")
					fa-file-pdf-o
				@elseif(in_array($attachment->mime, array('video/x-ms-asf', 'audio/mpeg')))
					fa-file-audio-o
				@else
					fa-file-o
				@endif"></i> 
				<a href="{{ action('AttachmentController@show', array($attachment->id)) }}">{{ $attachment->name }}</a> ({{ round($attachment->size/(1024*1024), 2) }} MB)
				@if(($attachment->mime == "video/x-ms-asf") && $is_win)
				<div class="media"> 
				    <object codebase="http://www.apple.com/qtactivex/qtplugin.cab" 
				        classid="clsid:6BF52A52-394A-11d3-B153-00C04F79FAA6" 
				        type="application/x-oleobject"> 
				        <param name="url" value="{{ action('AttachmentController@show', array($attachment->id)) }}"> 
				        <embed src="{{ action('AttachmentController@show', array($attachment->id)) }}" 
				            type="application/x-mplayer2" 
				            pluginspage="http://www.microsoft.com/Windows/MediaPlayer/"></embed> 
				    </object> 
				</div>
				@elseif($attachment->mime == "audio/mpeg")
				<button class="btn btn-primary btn-xs play-mp3" data-src="{{ action('AttachmentController@show', array($attachment->id)) }}"><i class="fa fa-play"></i> Play</button>
				@endif
				</p>
			@endforeach
			@endif
		</div>
	</div>
</div>

app/views/courses/show.blade.php
@extends('layout')

@section('breadcrumb')
	<li><a href="{{ action('CourseController@index') }}">Course Management</a></li>
	<li class="active">View Course</li>
@stop

@section('header')
	<div class="jumbotron">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-6">
					<h1>{{ $course->name }}</h1>
					<p>{{ $course->description }}</p>
				</div>
				@if($cu->role <= 1)
				<div id="main-header-actions" class="col-md-6">
					<a href="{{ route('courses.edit', array($course->id)) }}" class="btn btn-warning"><i class="fa fa-pencil"></i> Edit</a>
					{{ Form::open(array('action' => array('CourseController@destroy', $course->id), 'method' => 'delete')) }}
						<button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
					{{ Form::close() }}
				</div>
				@endif
			</div>
		</div>
	</div>
	<div id="main-header-tabs">
		<div class="container-fluid">
			<ul class="nav nav-tabs">
				<li @if($tabs == "lessons") class="active" @endif>
					<a href="{{ route('courses.show', array($course->id)) }}">Lessons @if($cu->role <= 2)<span class="badge">{{ $tab_count['syllabus'] or 0 }}</span>@endif</a>
				</li>
				<li @if($tabs == "exam") class="active" @endif>
					<a href="{{ route('courses.show.exam', array($course->id)) }}">Exams @if($cu->role <= 2)<span class="badge">{{ $tab_count['exam'] or 0 }}</span>@endif</a>
				</li>
			</ul>
		</div>
	</div>
@stop

@section('footer_js')
<script type="text/javascript">
$().ready(function(){
	$('.play-mp3').click(function(){
		$(this).after('<br><audio controls autoplay><source src="' + $(this).data('src') + '" type="audio/mpeg"></audio>');
		$(this).remove();
	});
});
</script>
@stop

@section('contents')
	<div class="row">
		<div class="col-md-6">
			<div class="panel-group" id="syllabus-list">
			@forelse($syllabuses as $syllabus)
				@if($cu->role == 3)
					@include('courses.panel', array('syllabus' => $syllabus, 'collapse' => true, 'new' => in_array($syllabus->id, $recent)))
				@else
					@include('courses.panel', array('syllabus' => $syllabus, 'collapse' => true))
					@endif
			@empty
				<div class="panel panel-default">
					<div class="panel-body">No {{ io($tabs == 'exam', 'exam', 'lesson') }} in this course yet.</div>
				</div>
			@endforelse
			</div>
		</div>
	</div>
@stop